#!/usr/bin/env python3
"""Build an executive deep-validation report for top fractal campaign winners."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

import gp_crypto_evolution as gp
from pairwise_regime_mixture_shadow_live import build_pairwise_plan, load_promotion_gate, load_strategy_bundle


ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = ROOT / "models"
DEFAULT_BASE_SUMMARY = MODELS_DIR / "gp_regime_mixture_btc_bnb_pairwise_repair_summary.json"
DEFAULT_MODEL_PATH = MODELS_DIR / "recent_6m_gp_vectorized_big_capped_rerun.dill"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Pressure top fractal campaign winners into an executive keep/watch/drop report.",
    )
    parser.add_argument(
        "--campaign-report",
        required=True,
        help="Campaign report generated by run_fractal_market_os_campaign.py",
    )
    parser.add_argument("--top-n", type=int, default=3)
    parser.add_argument("--equity", type=float, default=10000.0)
    parser.add_argument("--leverage", type=int, default=5)
    parser.add_argument("--base-summary", default=str(DEFAULT_BASE_SUMMARY))
    parser.add_argument("--model", default=str(DEFAULT_MODEL_PATH))
    parser.add_argument(
        "--report-out",
        default=str(MODELS_DIR / "gp_regime_mixture_btc_bnb_fractal_genome_market_os_deep_validation.json"),
    )
    return parser.parse_args()


def json_safe(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(k): json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_safe(v) for v in value]
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    return value


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(json_safe(payload), ensure_ascii=False, indent=2) + "\n")


def load_json(path: str | Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text())


def float_or_none(value: Any) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def metric_value(selected: dict[str, Any], window_key: str, field: str) -> float | None:
    return float_or_none((((selected.get("windows") or {}).get(window_key) or {}).get("aggregate") or {}).get(field))


def collect_candidate_entries(campaign_report: dict[str, Any], top_n: int) -> list[dict[str, Any]]:
    ordered: list[dict[str, Any]] = []
    seen: set[str] = set()

    def add(entry: dict[str, Any] | None) -> None:
        if not isinstance(entry, dict):
            return
        artifacts = entry.get("artifacts") or {}
        summary_path = str(artifacts.get("search_summary") or "")
        if not summary_path or summary_path in seen:
            return
        seen.add(summary_path)
        ordered.append(entry)

    for entry in (campaign_report.get("top_candidates") or [])[: max(int(top_n), 1)]:
        add(entry)
    for entry in (campaign_report.get("best_by_observation_mode") or {}).values():
        add(entry)
    for entry in (campaign_report.get("best_by_label_horizon") or {}).values():
        add(entry)
    return ordered


def classify_candidate(record: dict[str, Any]) -> tuple[str, list[str]]:
    blockers: list[str] = []
    decision = record.get("decision") or {}
    metrics = record.get("metrics") or {}

    if bool(decision.get("ready_for_merge", False)):
        return "keep", blockers
    if not bool(metrics.get("wf1_passed", False)):
        blockers.append("wf1_failed")
    if not bool(metrics.get("target_060_passed", False)):
        blockers.append("target_060_failed")
    if not bool(metrics.get("final_oos_passed", False)):
        blockers.append("final_oos_failed")
    if not bool(metrics.get("stress_gate_passed", False)):
        blockers.append("stress_gate_failed")

    recent_6m = float_or_none(metrics.get("recent_6m_worst_daily")) or 0.0
    full_4y = float_or_none(metrics.get("full_4y_worst_daily")) or 0.0
    full_4y_mdd = float_or_none(metrics.get("full_4y_mdd")) or 1.0
    latest_reserve = float_or_none(metrics.get("latest_fold_stress_reserve_score")) or 0.0

    if bool(metrics.get("wf1_passed", False)) and recent_6m >= 0.006 and full_4y >= 0.0045 and full_4y_mdd <= 0.15:
        return "watch", blockers
    if bool(metrics.get("wf1_passed", False)) and latest_reserve > 0.0 and full_4y_mdd <= 0.19:
        return "watch", blockers
    return "drop", blockers


def build_candidate_record(
    entry: dict[str, Any],
    *,
    df_all: pd.DataFrame,
    base_summary: Path,
    model_path: Path,
    equity: float,
    leverage: int,
) -> dict[str, Any]:
    artifacts = entry.get("artifacts") or {}
    summary_path = Path(artifacts["search_summary"])
    pipeline_path = Path(artifacts["pipeline_report"])
    summary = load_json(summary_path)
    pipeline = load_json(pipeline_path)
    selected = summary.get("selected_candidate") or {}
    decision = (pipeline.get("decision") or {})

    pairs = tuple(summary.get("pairs") or ("BTCUSDT", "BNBUSDT"))
    bundle = load_strategy_bundle(summary_path, base_summary, model_path)
    plan = build_pairwise_plan(
        df_all,
        pairs,
        bundle,
        equity=float(equity),
        execute=False,
        leverage=int(leverage),
        exchange=None,
    )
    promotion_gate = load_promotion_gate(pipeline_path)
    metrics = {
        "observation_mode": selected.get("observation_mode"),
        "label_horizon": selected.get("label_horizon"),
        "tree_depth": selected.get("tree_depth"),
        "logic_depth": selected.get("logic_depth"),
        "recent_2m_worst_daily": metric_value(selected, "recent_2m", "worst_pair_avg_daily_return"),
        "recent_6m_worst_daily": metric_value(selected, "recent_6m", "worst_pair_avg_daily_return"),
        "full_4y_worst_daily": metric_value(selected, "full_4y", "worst_pair_avg_daily_return"),
        "recent_2m_mdd": abs(metric_value(selected, "recent_2m", "worst_max_drawdown") or 0.0),
        "recent_6m_mdd": abs(metric_value(selected, "recent_6m", "worst_max_drawdown") or 0.0),
        "full_4y_mdd": abs(metric_value(selected, "full_4y", "worst_max_drawdown") or 0.0),
        "wf1_passed": bool(((selected.get("robustness") or {}).get("wf_1") or {}).get("passed", False)),
        "stress_survival_mean": float_or_none((selected.get("robustness") or {}).get("stress_survival_rate_mean")),
        "latest_fold_stress_reserve_score": float_or_none((selected.get("robustness") or {}).get("latest_fold_stress_reserve_score")),
        "target_060_passed": bool((((selected.get("validation") or {}).get("profiles") or {}).get("target_060") or {}).get("passed", False)),
        "progressive_passed": bool((((selected.get("validation") or {}).get("profiles") or {}).get("progressive_improvement") or {}).get("passed", False)),
        "final_oos_passed": bool((((selected.get("validation") or {}).get("profiles") or {}).get("final_oos") or {}).get("passed", False)),
        "validation_gate_passed": bool(decision.get("validation_gate_passed", False)),
        "market_os_gate_passed": bool(decision.get("market_os_gate_passed", False)),
        "stress_gate_passed": bool(decision.get("stress_gate_passed", False)),
    }

    record = {
        "seed": entry.get("seed"),
        "artifacts": artifacts,
        "decision": {
            "status": decision.get("status"),
            "ready_for_merge": bool(decision.get("ready_for_merge", False)),
            "ready_for_live": bool(decision.get("ready_for_live", False)),
            "promotion_gate_status": promotion_gate.get("status"),
        },
        "metrics": metrics,
        "current_runtime": {
            "market_day": plan.get("market_day"),
            "effective_day": plan.get("effective_day"),
            "target_weights": plan.get("target_weights"),
            "gross_target_weight": plan.get("gross_target_weight"),
            "active_leaf": (plan.get("selected_candidate") or {}).get("active_leaf"),
            "runtime_context": (plan.get("selected_candidate") or {}).get("runtime_context"),
        },
    }
    band, blockers = classify_candidate(record)
    record["decision_band"] = band
    record["blockers"] = blockers
    return record


def rank_records(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    def key(item: dict[str, Any]) -> tuple[Any, ...]:
        metrics = item.get("metrics") or {}
        return (
            1 if item.get("decision_band") == "keep" else 0,
            1 if item.get("decision_band") == "watch" else 0,
            1 if bool(metrics.get("wf1_passed", False)) else 0,
            float_or_none(metrics.get("recent_6m_worst_daily")) or float("-inf"),
            float_or_none(metrics.get("full_4y_worst_daily")) or float("-inf"),
            float_or_none(metrics.get("latest_fold_stress_reserve_score")) or float("-inf"),
            -(float_or_none(metrics.get("full_4y_mdd")) or float("inf")),
        )

    return sorted(records, key=key, reverse=True)


def best_by(records: list[dict[str, Any]], field: str) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for record in rank_records(records):
        value = (record.get("metrics") or {}).get(field)
        if value is None:
            continue
        out.setdefault(str(value), record)
    return out


def main() -> None:
    args = parse_args()
    campaign_report = load_json(args.campaign_report)
    candidate_entries = collect_candidate_entries(campaign_report, int(args.top_n))
    if not candidate_entries:
        raise RuntimeError("No candidates found in campaign report.")

    first_summary = load_json(candidate_entries[0]["artifacts"]["search_summary"])
    pairs = tuple(first_summary.get("pairs") or ("BTCUSDT", "BNBUSDT"))
    df_all = gp.load_all_pairs(pairs=list(pairs), start=None, end=None, refresh_cache=False)

    records = [
        build_candidate_record(
            entry,
            df_all=df_all,
            base_summary=Path(args.base_summary),
            model_path=Path(args.model),
            equity=float(args.equity),
            leverage=int(args.leverage),
        )
        for entry in candidate_entries
    ]
    ranked = rank_records(records)
    report = {
        "strategy_class": "fractal_market_os_deep_validation",
        "campaign_report": str(Path(args.campaign_report).resolve()),
        "candidate_count": len(ranked),
        "kept_count": sum(1 for item in ranked if item.get("decision_band") == "keep"),
        "watch_count": sum(1 for item in ranked if item.get("decision_band") == "watch"),
        "drop_count": sum(1 for item in ranked if item.get("decision_band") == "drop"),
        "best_candidate": ranked[0] if ranked else None,
        "best_by_observation_mode": best_by(ranked, "observation_mode"),
        "best_by_label_horizon": best_by(ranked, "label_horizon"),
        "records": ranked,
    }
    output_path = Path(args.report_out)
    write_json(output_path, report)
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
